#!/bin/sh
out_name=`xrandr -q | awk '/connected primary/ {print $1}'`
avail_modes=`xrandr -q | awk '/[0-9]x[0-9]/ && !/[a-wyzA-WYZ]/'`
if [ -z "$1" ];then
	printf "$avail_modes\n"
	printf "Type one of the above modes (e.g. \"1920x1080\"): "
	read res
else
	res="$1"
fi
xrandr --output $out_name --mode $res
