#!/bin/sh
mainfolder=$1
echo $mainfolder
find $mainfolder -type d -exec echo {} \; -exec chmod o-rw {} \;
echo 2
find $mainfolder -regextype awk -regex "\.*/.*\.(7z|zip|tar|gz|bz2|lzip|lz|lzo|lzma|pk3|zlib|sb|sb2|sb3|viv|rar|arj|deb|pkg|rpm|z|mp3|flac|wav|aif|cda|mid|midi|mpa|m4a|ogg|wma|wpl|mp4|ogv|avi|mkv|3g2|3gp|flv|h264|m4v|mov|mpg|mpeg|rm|swf|vob|wmv|png|jpg|jpeg|bmp|ico|gif|ps|svg|tif|tiff|tga|c4d|blender|veg|ae|psd|ai|xfc|txt|js|c|cpp|a|h|hpp|java|jar|class|cs|asm|au3|asp|cer|cfm|css|htm|html|xml|jsp|part|st|php|rss|xhtml|mdl|mtl|obj|ini|cfg|flp|reg|lnk|dwg|xls|xlsm|xlsx|pps|ppt|pptx|tex|wpd|pdf|rtf|doc|docx|odt|ods|odp|iso|bin|dmg|toast|vcd|csv|dat|dbf|db|bsp|mdb|sav|zds|sql|log|email|eml|msg|oft|ost|pst|vcf|fnt|fon|otf|ttf|bak|cab|cpl|cur|dll|dmp|drv|icns|sys|tmp|mrp|act|sfk|osz|osk|diskname)" -exec echo {} \; -exec chmod -x {} \;
