#!/bin/python
import sys
def print_convs(x):
    i=int(x,16)
    print(i)
    print(bin(i))
    print(hex(i))
    print(oct(i))

if sys.argv[1].startswith("0x"):
    print_convs(sys.argv[1])
if sys.argv[1].startswith("0x"):
    print_convs(sys.argv[1])
if sys.argv[1].startswith("0x"):
    print_convs(sys.argv[1])
if sys.argv[1].startswith("0x"):
    print_convs(sys.argv[1])
