#!/bin/sh
#old name: "last_added_ncmpcpp_getfattr"
mf='/I/Raccolte/music_files.txt'
md='/I/Raccolte/Musica'
arg=$1
IFS=$'\n'

resume=0
update=0
while getopts uh opt;do #r #per -r (resume)
	case $opt in
		#r)resume=1;;
		u)update=1;;
		h)	echo -ne "Usage: $0 [opt]\n";
			#echo -ne "  -n\t\tdon't be verbose (dont't print processed files)\n";
			#echo -ne "  -r \tresume after populating playlist\n";
			echo -ne "  -u \tupdate '$mf'\n";
			exit 0;;
		?)exit 2;;
	esac
done
#if [ "$arg" = "play" ];then
#	update=1
#fi


data_cmd=0
if [ "$(lsblk -o FSTYPE $(df -T "$md" | awk '/\/dev\//{print $2}') | tail -1)" == "ntfs" ];then
	data_cmd=1
fi
cd "$md"
if [ $update -eq 1 ];then
	for a in `find .`;do
		gr=$(grep -F "$a" "$mf")
		#echo $gr
		if [ -n "$gr" ];then
			continue
		else
			echo "adding $a to $mf"
			if [ $data_cmd -eq 1 ];then
				data=$(date -d @$(getfattr --only-values -n system.ntfs_crtime_be "$a" 2>/dev/null | perl -MPOSIX -0777 -ne '$t = unpack("Q>"); print $t/10000000-11644473600') +%Y-%m-%d_%H-%M-%S)
			else
				data=$(date -d "$(stat "$a" | nl | awk '$1 == 8 {print $3,$4}')" +%Y-%m-%d_%H-%M-%S)
			fi
			echo "$data \"$a\"" >> $mf
		fi
	done
fi

printf "csong\n"
echo $arg
if [ "$arg" = "add" ];then
	n=0
	for csong in `cat $mf | sort -nr | awk '!/^#/' | cut -c 1-2 --complement | tr -d '"' | awk '/\.mp3$|\.wav$|\.flac$|\.m4a$/ {print substr($0, 21)}'`;do
		#echo $csong
		is_there=`mpc -f '%file%' playlist | grep -F "$csong"`
		#echo $is_there
		if [ -z "$is_there" ];then
			mpc add "$csong"
			let n++
			mpc move `mpc status | perl -ne 'print "$1\n" if /#[0-9]+\/([0-9]+)/'` $n
			printf "added: $csong\n"
		fi
	done
	exit 0
fi

if [ "$arg" = "play" ];then
	mpc update >/dev/null
	mpc clear >/dev/null
	pwd
	n=0
	for csong in `cat $mf | sort -nr | awk '!/^#/' | cut -c 1-2 --complement | tr -d '"' | awk '/\.mp3$|\.wav$|\.flac$|\.m4a$/ {print substr($0, 21)}'`;do
		#echo $csong
		mpc add "$csong"
		let n++
		if [ $n -eq 100 ];then
			mpc random off
			mpc play
		fi
	done
	exit 0
fi
