#!/bin/sh
#IFS=$'\n'
#mpc clear
for a in /disks/I/Raccolte/Musica/*;do
	data=$(date -d @`getfattr --only-values -n system.ntfs_crtime_be "$a" 2>/dev/null | perl -MPOSIX -0777 -ne '$t = unpack("Q>"); print $t/10000000-11644473600'` +%Y-%m-%d_%H-%M-%S)
	songs+=$(printf "$data `basename \"$a\"`\n")
done
echo $songs


	#printf "$(date -d @$((`getfattr --only-values -n system.ntfs_crtime_be '$a' 2>/dev/null | perl -MPOSIX -0777 -ne '$t = unpack("Q>"); print $t/10000000-11644473600'`)) +%Y-%m-%d_%H-%M-%S)\n"
