#!/bin/sh
mf='/disks/I/Raccolte/music_files.txt'
md='/disks/I/Raccolte/Musica'

for a in "$md/*";do
	if [ -n "$(grep "$a" "$mf")" ];then
		continue
	else
		echo "adding $a to $mf"
		data=$(date -d @`getfattr --only-values -n system.ntfs_crtime_be "$a" 2>/dev/null | perl -MPOSIX -0777 -ne '$t = unpack("Q>"); print $t/10000000-11644473600'` +%Y-%m-%d_%H-%M-%S)
		echo "$data `basename \"$a\"`" >> $mf
	fi
done
printf "csong\n"
mpc update >/dev/null
mpc clear >/dev/null
cd "$md"
IFS=$'\n'
n=0
for csong in `cat $mf | sort -nr | awk '/\.mp3$|\.wav$|\.flac$|\.m4a$/ {print substr($0, 21)}'`;do
	mpc add "$csong"
	let n++
	if [ $n -eq 100 ];then
		mpc random off
		mpc play
	fi
done
