#!/bin/sh
program=$1
[[ -z $program ]] && printf "Usage: linkb [program to link]\n" && exit 1
ln -s $PWD/$program /bin/$program
echo linked $PWD/$program

#ln -s ~/linux-custom-scripts/$program /bin/$program
