#!/bin/sh
#macon
o="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 1 | head -n 1 | tr -d '\n')" #one
t="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 2 | head -n 1 | tr -d '\n')" #two
r="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 2 | head -n 1 | tr -d '\n')" #three
f="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 2 | head -n 1 | tr -d '\n')" #four
v="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 2 | head -n 1 | tr -d '\n')" #five
s="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 2 | head -n 1 | tr -d '\n')" #six
#custom
o="b$o"
#t="" #two
#r="" #three
#f="" #four
v="eb" #five
s="1c" #six
mac="$o:$t:$r:$f:$v:$s"
echo new mac: $mac
#exit 0
sudo ip link set dev enp3s0 down
sudo ip link set dev enp3s0 address $mac
sudo ip link set dev enp3s0 up
