#!/bin/bash
#n=$(xrandr -q | grep \\sconnected | wc -l)
IFS=$'\n'
eval $(xdotool getmouselocation --shell)
for i in $(xrandr -q | grep -Eo '[^ ]+\+[0-9]+\+[0-9]+' | sed 's/x\|+/ /g');do
	IFS=' '
	read -r w h ox oy < <(echo $i)
	echo w:$w h:$h ox:$ox oy:$oy
	if [ $X -lt $ox ];then
		echo in questo:${w}x$h $DISPLAY+$ox,$oy
	fi
	if [ $Y -lt $oy ];then
		ox=0
	fi
	IFS=$'\n'
done
