#!/bin/bash
n=$(xrandr -q | grep \\sconnected | wc -l)
IFS=$'\n'
for i in $(xrandr -q | grep -Eo '[^ ]+\+[0-9]+\+[0-9]+' | sed 's/x\|+/ /g');do
	IFS=' '
	read -r w h ox oy < <(echo $i)
	echo w:$w h:$h ox:$ox oy:$oy
	IFS=$'\n'
done
