#!/bin/bash
_pre() {
	echo _pre
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			mpc pause
			systemctl --user stop mpd.socket
			mpd --kill
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
		hybrid-sleep)
			echo hybrid-sleep
			mpc pause
			systemctl --user stop mpd.socket
			mpd --kill
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			mpc pause
			systemctl --user stop mpd.socket
			mpd --kill
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
	esac
}
_post() {
	echo _post
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			mount -va
			systemctl --user start mpd.socket
			;;
		hybrid-sleep)
			echo hybrid-sleep
			mount -va
			systemctl --user start mpd.socket
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			mount -va
			systemctl --user start mpd.socket
			;;
	esac
}
case $1 in
	pre)_pre $2;;
	post)_post $2;;
esac
touch /scsleep_cmds.txt__txt
sleep 60
