#!/bin/sh
tsleep=$1
[[ -z $1 ]] && printf "Usage: shatimer [countdown] [alarm repeats (optional)]\n" && exit 1
if [ -z $2 ];then
	reap=15
else
	reap=$2
fi
sleep $tsleep
for reee in `eval echo {1..$reap}`;do
	mpv /usr/share/shalarm/ring.wav >/dev/null 2>&1
	## same as
	# mpv ~/shalarm/data/ring.wav >/dev/null 2>/dev/null
	# mpv ~/shalarm/data/ring.wav 2>/dev/null>/dev/null
done
