#!/bin/sh

#IFS=$'\n'
#for LINE in `w -hs`
#do
#    USER=`echo $LINE | awk '{print $1}'`
#    USER_ID=`id -u $USER`
#    DISP_ID=`echo $LINE | awk '{print $8}'`
#    sudo -u $USER DISPLAY=$DISP_ID DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER_ID/bus notify-send "S.M.A.R.T Error ($SMARTD_FAILTYPE)" "$SMARTD_MESSAGE" --icon=dialog-warning -u critical
#done


sudo -u koraynilay DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus notify-send "S.M.A.R.T Error ($SMARTD_FAILTYPE)" "$SMARTD_MESSAGE" --icon=dialog-warning -u critical
