#!/bin/sh
#mpc | cat -n | awk '$1 == 2 {print $2}' | sed -e 's/\[//g' -e 's/\]//g'
#mpc | cat -n | awk '$1 == 1 {for(i=2;i<=NF;i++){print $i}}' | tr '\n' ' '
#appname=$(mpc | cat -n | awk '$1 == 2 {print $2,"-",$4}' | sed -e 's/\[//g' -e 's/\]//g')
dunstify -t 3000 -u LOW -r 2 -p -a "$(mpc | cat -n | awk '$1 == 2 {res=$2" - "$4;gsub(/\[|\]/,"",res)} $1 == 3 {rzsc=(($5 == "on")?"r":"")(($7 == "on")?"z":"")(($9 == "on")?"s":"")(($11 == "on")?"c":"")} END{print res" ["rzsc"]"}')" "$(mpc | cat -n | awk '$1 == 1 {for(i=2;i<=NF;i++){print $i}}' | tr '\n' ' ')"
