#!/bin/sh
newrt="$HOME/chrrr"
mntrt="$HOME/plip_chr"
#debug echo $newrt
#debug echo $mntrt
sudo mount --bind "$newrt" "$mntrt"
#--verbose
sudo arch-chroot $mntrt /bin/zsh -c "su -l koray"
sudo umount --recursive $mntrt
#--verbose
