#!/bin/sh
print_usage(){
	printf "Usage: $0 [options]\n"
	printf "  -a\tactivate chroot with specified parameters\n"
	printf "  -c\tcreate chroot with the other options\n"
	printf "  -n\tnew root (absolute path)\n"
	printf "  -m\tmount point for the root (absolute path)\n"
	printf "  -f\tuser home from where dotfiles are copied\n"
	printf "  -r\troot home from where dotfiles are copied\n"
	printf "  -p\tlist of packages to install\n"
	printf "  -u\tname of the user in the new root\n"
	printf "  -v\tprint variables\n"
	printf "  -h\tshow this help\n"
}

act=0
create=0
verbose=0
[[ -z $0 ]] && print_usage
#echo $UID
[[ $UID -ne 0 ]] && printf "This script needs root privileges.\n" && exit 5
while getopts n:m:f:r:p:u:cahv option;do
	case $option in
		a)act=1;;
		c)create=1;;
		v)verbose=1;;
		n)newrt=$OPTARG;;
		m)mntrt=$OPTARG;;
		f)homef=$OPTARG;;
		r)rootf=$OPTARG;;
		p)pkgs=$OPTARG;;
		u)usernr=$OPTARG;;
		h)print_usage;exit 0;;
		?)exit 1;;
	esac
done
newrt=${newrt:="$HOME/chrrr"}
mntrt=${mntrt:="$HOME/plip_chr"}
homef=${homef:="$HOME/linux-custom-scripts/chroot_stuff/users/koray"}
rootf=${rootf:="$HOME/linux-custom-scripts/chroot_stuff/users/root"}
pkgs=${pkgs:=('git' 'vim' 'zsh' 'which')}
pkgs=${pkgs#\(}
pkgs=${pkgs%\)}
usernr=${usernr:="koray"}
if [ $verbose -eq 1 ];then
	echo $newrt
	echo $mntrt
	echo $homef
	echo $rootf
	echo $pkgs
	echo $usernr
	printf "5 seconds timeout, press Control-C to cancel\r"
	sleep 5
fi
if [ $create -eq 1 ];then
	if [ ! -d $newrt ];then
		printf "New root folder doesn't exist, create it [y/n]? "
		read ans
		if [ "$ans" = "y" ];then
			mkdir -p $newrt
		fi
	fi
	if [ ! -d $mntrt ];then
		printf "New mount folder doesn't exist, create it [y/n]? "
		read ans
		if [ "$ans" = "y" ];then
			mkdir -p $mntrt
		fi
	fi
	pacstrap $newrt base $pkgs
	mount --bind "$newrt" "$mntrt"
	arch-chroot $mntrt /bin/bash -c "useradd -m $usernr;passwd $usernr"
	umount --recursive $mntrt
	cp -vr $homef/* $homef/.* "$newrt/home/$usernr/"
	cp -vr $rootf/* $rootf/.* "$newrt/root/"
	cp -vr /usr/share/terminfo $mntrt/usr/share/
	mount --bind "$newrt" "$mntrt"
	arch-chroot $mntrt /bin/zsh -c "chown -hR $usernr:$usernr /home/$usernr && su -l $usernr -c \"cd ~;./install_omz.sh;exit\""
	sleep 0.5
	umount --recursive $mntrt $newrt
fi
if [ $act -eq 1 ];then
	mount --bind "$newrt" "$mntrt"
	arch-chroot $mntrt /bin/zsh -c "su -l $usernr"
	umount --recursive $mntrt
fi
