#!/bin/bash
_mpduser='koraynilay'
_pre() {
	echo _pre
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			sleep 3
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs|fat/ {print $1}')
			;;
		hybrid-sleep)
			echo hybrid-sleep
			sleep 3
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs|fat/ {print $1}')
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			sleep 3
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs|fat/ {print $1}')
			;;
	esac
}
_post() {
	echo _post
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			mount -a
			;;
		hybrid-sleep)
			echo hybrid-sleep
			mount -a
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			mount -a
			;;
	esac
}
case $1 in
	pre)_pre $2;;
	post)_post $2;;
esac
touch /_000a_scsleep_cmds.txt__$(date +%0N)
echo end
sleep 60
exit $?
