#!/bin/bash
_mpduser='koraynilay'
_pre() {
	echo _pre
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			sudo -u koraynilay mpd --kill
			#su -c 'systemctl --user stop mpd' $_mpduser
			sleep 1
			umount $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
		hybrid-sleep)
			echo hybrid-sleep
			su -c 'systemctl --user stop mpd' $_mpduser
			sleep 1
			umount -R $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			su -c 'systemctl --user stop mpd' $_mpduser
			sleep 1
			umount -R $(lsblk -o PATH,FSTYPE | awk '/ntfs/ {print $1}')
			;;
	esac
}
_post() {
	echo _post
	case $1 in
		suspend)echo suspend;;
		hibernate)
			echo hibernate
			mount -a
			sleep 1
			su -c 'systemctl --user start mpd' $_mpduser
			;;
		hybrid-sleep)
			echo hybrid-sleep
			mount -a
			sleep 1
			su -c 'systemctl --user start mpd' $_mpduser
			;;
		suspend-then-hibernate)
			echo suspend-then-hibernate
			mount -a
			sleep 1
			su -c 'systemctl --user start mpd' $_mpduser
			;;
	esac
}
case $1 in
	pre)_pre $2;;
	post)_post $2;;
esac
touch /_000a_scsleep_cmds.txt__$(date +%0N)
echo end
sleep 60
exit $?
