#!/bin/sh
deskcat='cava_desktop'
deskpct='peaclock_desktop'
geomcava='370 260' #width height
geompeaclock='470 260' #width height
poscava='1550 800' #absolute x y (from top_left of monitor)
pospeaclock='10 440' #absolute x y (from top_left of monitor)
cava_id=$(xdotool search --name "^$deskcat\$")
peaclock_id=$(xdotool search --name "^$deskpct\$")
if [ -n $cava_id ];then
	xdotool windowkill $cava_id
fi
if [ -n $peaclock_id ];then
	xdotool windowkill $peaclock_id
fi
nice -n 19 termite -c ~/.config/termite/config_desktop -t $deskcat -e 'cava' >/dev/null 2>&1 &!
nice -n 19 termite -c ~/.config/termite/config_desktop -t $deskpct -e 'peaclock' >/dev/null 2>&1 &!
sleep 0.2
cava_id=$(xdotool search --name "^$deskcat\$")
peaclock_id=$(xdotool search --name "^$deskpct\$")

xdotool windowunmap --sync $cava_id
xdotool set_window --overrideredirect 1 $cava_id
xdotool windowmap --sync $cava_id

xdotool windowunmap --sync $peaclock_id
xdotool set_window --overrideredirect 1 $peaclock_id
xdotool windowmap --sync $peaclock_id

xdotool windowsize --sync $cava_id $geomcava
xdotool windowsize --sync $peaclock_id $geompeaclock
xdotool windowmove --sync $cava_id $poscava
xdotool windowmove --sync $peaclock_id $pospeaclock

xdo lower $cava_id
xdo lower $peaclock_id

sleep 1
exit 0
