#!/bin/sh
[[ $UID -ne 0 ]] && echo this script needs root privileges && exit 1
#macoff
mac="b0:6e:bf:33:eb:1c"
echo new mac: $mac
ip link set dev enp3s0 down
ip link set dev enp3s0 address $mac
ip link set dev enp3s0 up
