#!/bin/sh
curl -sS https://www.archlinux.org/news/ | \
awk '(/td class/ || /title/ || /<td>[0-9]+-[0-9]+-[0-9]+<\/td>/) && \
!/?page=[0-9]/ && \
!/td class/ && \
!/title="[^V]/ && \
!/(<|<\/)title>/ \
{gsub(/((<\/|<)td>)|(title="View: .*">)|(<\/a>)/,""); \
print}' | \
\
sed 's/&gt;/>/g' | \
\
awk 'BEGIN {n=0} \
{n+=1; \
if(n==9) \
	{exit}; \
sub(/\s{16}/,""); \
print}'
#awk '{sub(/\s{16}/,"");print}'
#| awk '/< / {sub(/<\s+/,"");print}'

printf "\n"
