#!/bin/sh
dialog_id=`xdotool search --name "^archlinux_updates_script$"`
xdotool windowkill $dialog_id
termite -t "archlinux_updates_script" -e updates_dialog_text 2>/dev/null
sleep 5
mapunmap_updates.sh
exit 0
