#!/bin/sh
aur_helper='yay'

answ(){
	printf "Update?: "
	read ans
	ans="${ans//$'\n'/ }"
	if [[ "$ans" == "y" || $ans == "yes" ]];then
		$aur_helper
	else
		main
	fi
}
main(){
	clear
	printf "Updates available:\n\n"
	updates_news
	yay -Pw
	sudo checkupdates
	yay -Qu
	exit_code=$?
	if [ $exit_code -eq 2 ];then
		return 0
	fi
	answ
}
trap main INT
while true;do
	main
	sleep 600 &
	wait $!
done
